version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html_sites:/usr/share/nginx/html

  site1:
    image: nginx:alpine
    volumes:
      - ./html_sites/site1.html:/usr/share/nginx/html/site1.html

  site2:
    image: nginx:alpine
    volumes:
      - ./html_sites/site2.html:/usr/share/nginx/html/site2.html

  site3:
    image: nginx:alpine
    volumes:
      - ./html_sites/site3.html:/usr/share/nginx/html/site3.html

